server:
  port: '8050'

# JPA Setting
spring:
  datasource: #DB
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DOCKER_DB_USERNAME}
    url: jdbc:mariadb://${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${KOKONUT_DB_DBNAME}
    password: ${DOCKER_DB_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: '6379'
  data:
    redis:
      repositories:
        enabled: false

# JWT_SECRET_STRING : echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
jwt:
  secret: ${JWT_Secret}

#Custom
kokonut_aws_kms_secret: ${KOKONUT_AWS_KMS_SECRET}
kokonut_aws_kms_access: ${KOKONUT_AWS_KMS_ACCESS}
kokonut_aws_kms_id: ${KOKONUT_AWS_KMS_ID}

kokonut_mail_host: ${KOKONUT_MAIL_HOST}

otp:
  hostUrl: ${KOKONUT_OTP_URL}

# iamport 관련 값
kokonut_iamport_key: ${KOKONUT_IAMPORT_KEY}
kokonut_iamport_secret: ${KOKONUT_IAMPORT_SECRET}

# niceId 관련 필요한 값
kokonut_nice_id: ${KOKONUT_NICE_ID}
kokonut_nice_secret: ${KOKONUT_NICE_SECRET}
kokonut_nice_product: ${KOKONUT_NICE_PRODUCT}
kokonut_nice_access: ${KOKONUT_NICE_ACCESS}

# naver cloud 관련 값
kokonut_ncloud_serviceId: ${KOKONUT_NCLOUD_SERVICEID}
kokonut_ncloud_accessKey: ${KOKONUT_NCLOUD_ACCESSKEY}
kokonut_ncloud_secretKey: ${KOKONUT_NCLOUD_SECRETKEY}
kokonut_ncloud_primaryKey: ${KOKONUT_NCLOUD_PRIMARYKEY}
kokonut_ncloud_categoryCode: ${KOKONUT_NCLOUD_CATEGORYCODE}

#stibee
kokonut_stibee_apiKey: ${KOKONUT_STIBEE_APIKEY}
